global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'user_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:9091']
        labels:
          application: 'User Service Application'

  - job_name: 'config-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'localhost:8888' ]
        labels:
          application: 'Config Server Application'