global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'notification_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8083']
        labels:
          application: 'Notification Service Application'
  - job_name: 'order_status_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8085']
        labels:
          application: 'Order Status Service Application'
  - job_name: 'payment_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:9092']
        labels:
          application: 'Payment Service Application'
  - job_name: 'chat_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:9093']
        labels:
          application: 'Chat Service Application'
  - job_name: 'api_gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8080']
        labels:
          application: 'Api gateway'
  - job_name: 'eureka_server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8761']
        labels:
          application: 'Eureka server'
  - job_name: 'config_server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8888']
        labels:
          application: 'Config server'
  - job_name: 'service_provider_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8081']
        labels:
          application: 'Service provider service'  
  - job_name: 'feedback_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8082']
        labels:
          application: 'Feedback service'
  - job_name: 'user_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:9091']
        labels:
          application: 'User service'
  - job_name: 'user_authenticate_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:9094']
        labels:
          application: 'User authenticate service'
  - job_name: 'booking_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:9097']
        labels:
          application: 'Booking service'
          