version: "3"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    network_mode: host

  feedback-service:
    image: feedback-service
    container_name: feedback-service
    ports:
      - 8082:8082
    depends_on:
      - eureka-server
      - mongodb
    network_mode: host
    hostname:
      -mongodb

  eureka-server:
    image: eureka-server
    container_name: eureka-server
    network_mode: host
    ports:
      - 8761:8761

  api-gateway:
    image: api-gateway
    container_name: api-gateway
    ports:
      - 8080:8080
    depends_on:
      - feedback-service
    network_mode: host
    environment:
      SPRING_PROFILES_ACTIVE: path
      SPRING_CLOUD_GATEWAY_ROUTES[0]_URI: http://localhost:8082
      SPRING_CLOUD_GATEWAY_ROUTES[0]_ID: FEEDBACK_SERVICE
      SPRING_CLOUD_GATEWAY_ROUTES[0]_PREDICATES[0]: Path= /api/feedback/**

  ## Prometheus
  prometheus:
    image: prom/prometheus:v2.37.1
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    depends_on:
      - feedback-service
    network_mode: host

  grafana:
    image: grafana/grafana-oss:8.5.2
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    network_mode: host
